title: <p align="center"> Palla Mohana Silpa </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  AProficient in systematically extract information from large set of data.Proficient in Big data analytics.
  Excellent code analysis, debugging, and technical problem-solving skills.
  <br>
  </p>



theme: jekyll-theme-minimal
