title: Palla Mohana Silpa
logo: assets/img/ProfilePhoto.jpg
description: I have 3+ Years of total IT experience in Big Data Analysis and Data
Management.Proficient in systematically extract information from large set of data.Proficient in Big data analytics.Excellent code analysis, debugging, and technical problem-solving skills.Excellent communication skills both verbal and written.Experience in working with Agile Methodology.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
